<?php

// Language definitions used in admin-groups.php
$lang_admin_groups = array(

'Must enter title message'		=>	'Debes de introducir el nombre del grupo.',
'Title already exists message'	=>	'Ya existe el grupo <strong>%s</strong>.',
'Default group redirect'		=>	'Grupo por defecto activado. Redirigiendo …',
'Cannot remove default message'	=>	'El grupo por defecto no puede ser borrado. Para hacerlo tendrás que poner antes a otro como el grupo por defecto.',
'Group removed redirect'		=>	'Grupo borrado. Redirigiendo …',
'Group added redirect'			=>	'Grupo añadido. Redirigiendo …',
'Group edited redirect'			=>	'Grupo actualizado. Redirigiendo …',

'Add groups head'				=>	'Añadir/configurar grupos',
'Add group subhead'				=>	'Añadir nuevo grupo',
'New group label'				=>	'Añadir grupo usando como base ',
'New group help'				=>	'Seleccione un grupo para usar sus valores para el nuevo grupo. En la próxima pagina podrá editar los permisos.',
'Default group subhead'			=>	'Fijar grupo por defecto',
'Default group label'			=>	'Grupo por defecto',
'Default group help'			=>	'Este sera el grupo al que se añadirán los nuevos usuarios. Por motivos de seguridad el grupo por defecto no puede ser el de moderadoes o administradores.',
'Existing groups head'			=>	'Grupos existentes',
'Edit groups subhead'			=>	'Editar/borrar grupos',
'Edit groups info'				=>	'Los grupos predefinidos Invitados, Administradores, Moderadores y Usuarios no pueden ser borrados, sin embargo, pueden ser editados. En algunos grupos hay permisos que no pueden ser editados(p.e. los permisos para <em>editar mensaje</em> para los visitantes). Los administradores siempre tendrán todos los permisos.',
'Edit link'						=>	'Editar',
'Delete link'					=>	'Borrar',
'Group delete head'				=>	'Borrar grupo',
'Confirm delete subhead'		=>	'Confirmar borrado de grupo',
'Confirm delete info'			=>	'¿Estas seguro de querer borrar el grupo <strong>%s</strong>?',
'Confirm delete warn'			=>	'!Atención! Una vez borrado, no podrás recuperarlo.',
'Delete group head'				=>	'Borrar grupo',
'Move users subhead'			=>	'Mover miembros actuales del grupo',
'Move users info'				=>	'El grupo <strong>%s</strong> tiene actualmente <strong>%s</strong> miembros. Por favor, elija a los usuarios que serán asignados a otro grupo tras borrar el grupo.',
'Move users label'				=>	'Mover usuarios a',
'Delete group'					=>	'Borrar grupo',

'Group settings head'			=>	'Configuración del grupo',
'Group settings subhead'		=>	'Configura los permisos y opciones del grupo',
'Group settings info'			=>	'Abajo se muestran las opciones por defecto del grupo. Estas opciones no se aplicaran a los foros que tengan permisos especiales.',
'Group title label'				=>	'Nombre del grupo',
'User title label'				=>	'Titulo del usuario',
'User title help'				=>	'Este titulo se mostrara en lugar del que tenga el usuario. Dejar en blanco para mostrar el titulo o rango por defecto.',
'Mod privileges label'			=>	'Permisos de moderador',
'Mod privileges help'			=>	'Los miembros tendrán permisos de moderador y podrá moderar uno o mas foros. Esto se hace desde el panel del(os) usuario(s).',
'Edit profile label'			=>	'Editar usuarios',
'Edit profile help'				=>	'Si están activos los permisos de moderador, los miembros podrán editar el perfil de los usuarios.',
'Rename users label'			=>	'Renombrar usuarios',
'Rename users help'				=>	'Si están activos los permisos de moderador, los miembros podrán renombrar el nombre de los usuarios',
'Change passwords label'		=>	'Cambiar contraseñas',
'Change passwords help'			=>	'Si están activos los permisos de moderador, los miembros podrán cambiar las contraseñas de los usuarios.',
'Ban users label'				=>	'Banear',
'Ban users help'				=>	'Si están activos los permisos de moderador, los miembros de este grupo podrán banear usuarios.',
'Read board label'				=>	'Leer foro',
'Read board help'				=>	'Los miembros podrán leer los foros. Esta opción se aplicara a todo el foro y no le afectaran los persmisos de ellos. Si elijes no, el usuario solo podrá ver Entrar, Salir y Registrar.',
'View user info label'			=>	'Ver información del usuario',
'View user info help'			=>	'Los miembros podrán ver la lista y el perfil de los usuarios.',
'Post replies label'			=>	'Responder temas',
'Post replies help'				=>	'Los miembros podrán responder los mensajes de los temas.',
'Post topics label'				=>	'Crear temas',
'Post topics help'				=>	'Los miembros podrán crear nuevos temas.',
'Edit posts label'				=>	'Editar mensajes',
'Edit posts help'				=>	'Los miembros podrán editar los mensajes del foro.',
'Delete posts label'			=>	'Borrar mensajes',
'Delete posts help'				=>	'Los miembros podrán borrar mensajes del foro.',
'Delete topics label'			=>	'Borrar temas',
'Delete topics help'			=>	'Los miembros podrán borrar temas (mensajes incluidos).',
'Set own title label'			=>	'Ajustar titulo del usuario',
'Set own title help'			=>	'Los miembros podrán editar el titulo de los usuarios.',
'User search label'				=>	'Usar busqueda',
'User search help'				=>	'Los miembros podrán realizar búsquedas en el foro.',
'User list search label'		=>	'Buscar usuarios',
'User list search help'			=>	'Los miembros podrán buscar en la lista de usuarios.',
'Send e-mails label'			=>	'Enviar correos',
'Send e-mails help'				=>	'Los miembros podrán enviar correos a otros usurios.',
'Post flood label'				=>	'Intervalo entre mensajes',
'Post flood help'				=>	'Tiempo en segundos que tendrán que esperar entre mensajes. Poner a 0 para deshabilitarlo.',
'Search flood label'			=>	'Intervalo entre búsquedas',
'Search flood help'				=>	'Tiempo en segundos que tendrán que esperar entre búsquedas. Poner a 0 para deshabilitarlo.',
'E-mail flood label'			=>	'Intervalo entre correos',
'E-mail flood help'				=>	'Tiempo en segundos que tendrán que esperar entre enviar correos. Poner a 0 para deshabilitarlo.',
'Moderator info'				=>	'Terga en cuenta que para que un usuario tenga permisos de moderador, estos deben de ser activados desde el panel de usuarios.',

);
