<?php

// Language definitions used in admin-users.php
$lang_admin_users = array(

'Non numeric message'		=>	'Introdujiste un valor no numérico en un campo numérico.',
'Invalid date time message'	=>	'Introdujiste una fecha/hora invalida.',
'Not verified'				=>	'No verificado',
'User search head'			=>	'Buscar usuario',
'User search subhead'		=>	'Introduzca un criterio de búsqueda',
'User search info'			=>	'Buscar usuarios en la base de datos. Puedes usar el carácter * para refinar la búsqueda.',
'Username label'			=>	'Nombre del usuario',
'E-mail address label'		=>	'Dirección de correo',
'Title label'				=>	'Titulo',
'Real name label'			=>	'Nombre real',
'Website label'				=>	'Pagina web',
'Jabber label'				=>	'Jabber',
'ICQ label'					=>	'ICQ',
'MSN label'					=>	'MSN Messenger',
'AOL label'					=>	'AOL IM',
'Yahoo label'				=>	'Yahoo Messenger',
'Location label'			=>	'Localización',
'Signature label'			=>	'Firma',
'Admin note label'			=>	'Nota del administrador',
'Posts more than label'		=>	'Numero de mensajes mayor que',
'Posts less than label'		=>	'Numero de mensajes menor que',
'Last post after label'		=>	'Ultimo post después del',
'Date help'					=>	'(dd-mm-yyyy hh:mm:ss)',
'Last post before label'	=>	'Ultimo post antes del',
'Registered after label'	=>	'Registrado después del',
'Registered before label'	=>	'Registrado antes del',
'Order by label'			=>	'Ordenar por',
'Order by username'			=>	'Nombre de usuario',
'Order by e-mail'			=>	'Correo',
'Order by posts'			=>	'Numero de mensajes',
'Order by last post'		=>	'Ultimo mensaje',
'Order by registered'		=>	'Registrado',
'Ascending'					=>	'Ascendente',
'Descending'				=>	'Descendente',
'User group label'			=>	'Grupo del usuario',
'All groups'				=>	'Todos los grupos',
'Unverified users'			=>	'Usuarios sin verificar',
'Submit search'				=>	'Buscar',
'IP search head'			=>	'Buscar IP',
'IP search subhead'			=>	'Introduzca una dirección IP a buscar',
'IP address label'			=>	'Dirección IP',
'IP address help'			=>	'La dirección IP a buscar en la base de datos.',
'Find IP address'			=>	'Buscar dirección IP',

'Results head'				=>	'Resultados de la búsqueda',
'Results username head'		=>	'Nombre del usuario',
'Results e-mail head'		=>	'Correo',
'Results title head'		=>	'Titulo/Estado',
'Results posts head'		=>	'Mensaje',
'Results admin note head'	=>	'Nota del administrador',
'Results actions head'		=>	'Acciones',
'Results IP address head'	=>	'Dirección IP',
'Results last used head'	=>	'Ultima vez que entro',
'Results times found head'	=>	'Veces encontrado',
'Results action head'		=>	'Acción',
'Results find more link'	=>	'Buscar mas usuarios con esta IP',
'Results no posts found'	=>	'Actualmente no hay mensajes de este usuario en el foro.',
'Bad IP message'			=>	'La dirección IP introducida no esta bien formateada.',
'Results view IP link'		=>	'Ver estadísticas IP',
'Results show posts link'	=>	'Mostrar mensajes',
'Results guest'				=>	'Invitado',
'Results no IP found'		=>	'No se encontró esta dirección IP en la base de datos.',
'No match'					=>	'No se encontró ningún resultado'

);
