<?php

// Language definitions used in admin-options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'HTTP_REFERER invalido. Si moviste el foro o cambiaste el dominio, tienes que editar la Base URL manualmente en la base de datos (mira el valor de o_base_url en la tabla de configuración) y borrar la caché eliminando todos los archivos *.php del directorio /cache.',
'Must enter title message'			=>	'Debes introducir un título del foro.',
'Invalid e-mail message'			=>	'La dirección de correo del administrador no es válida.',
'Invalid webmaster e-mail message'	=>	'La dirección de correo del webmaster no es válida.',
'Enter announcement here'			=>	'Introduce el anuncio aquí.',
'Enter rules here'					=>	'Introduce las normas aquí.',
'Default maintenance message'		=>	'Los foros están en mantenimiento. Por favor, vuelve en unos minutos.',
'Timeout error message'				=>	'El valor de "tiempo de espera en línea" debe de ser menor que el de "tiempo de espera de visitas".',
'Options updated redirect'			=>	'Opciones actualizadas. Redirigiendo...',
'Options head'						=>	'Opciones',

// Essentials section
'Essentials subhead'				=>	'Esenciales',
'Board title label'					=>	'Título del foro',
'Board title help'					=>	'El título del foro (se mostrará arriba en todas las páginas). Este campo <strong>no</strong> puede contener código HTML.',
'Board desc label'					=>	'Descripción del foro',
'Board desc help'					=>	'Una descripción corta del foro (se mostrará arriba en todas las páginas). Este campo puede contener código HTML.',
'Base URL label'					=>	'URL Base',
'Base URL help'						=>	'La URL completa del foro, sin barra al final (p.e. http://www.midominio.com/foros). Esto <strong>debe</strong> ser correcto para que las funciones de moderación y administración funcionen. Si obtienes errores de "Referer no válido", es probablemente incorrecto.',
'Timezone label'					=>	'Zona horaria por defecto',
'Timezone help'						=>	'La zona horario por defecto para los visitantes y los usuarios que no cambien este valor.',
'DST label'							=>	'Horario de verano',
'DST help'							=>	'Comprueba si se está en horario de verano (1 hora más).',
'Language label'					=>	'Idioma por defecto',
'Language help'						=>	'El idioma por defecto para los visitantes y los usuarios que no cambien este valor. Si borras un idioma, éste se borrara automáticamente de la lista.',
'Default style label'				=>	'Tema por defecto',
'Default style help'				=>	'El tema por defecto para los visitantes y los usuarios que no cambien este valor.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'Fecha y timeouts',
'Time format label'					=>	'Formato de hora',
'PHP manual'						=>	'manual de PHP',
'Time format help'					=>	'[Formato actual: %s]. Consulta el %s para conocer las opciones de formato.',
'Date format label'					=>	'Formato de fecha',
'Date format help'					=>	'[Formato actual: %s]. Consulta el %s para conocer las opciones de formato.',
'Visit timeout label'				=>	'Timeout de visitas',
'Visit timeout help'				=>	'Número de segundos que un usuario ha de estar inactivo para que su fecha de última visita se actualizada (afecta principalmente al aviso de nuevos mensajes).',
'Online timeout label'				=>	'Timeout de conexión',
'Online timeout help'				=>	'Número de segundos que un usuario ha de estar inactivo para ser eliminado de la lista de usuarios activos.',
'Redirect time label'				=>	'Tiempo de redirección',
'Redirect time help'				=>	'Numero de segundos a esperar al redirigir. Si el valor es 0, no se mostrará la página de redirección (no recomendado).',

// Display Section
'Display subhead'					=>	'Vista',
'Version number label'				=>	'Mostrar versión',
'Version number help'				=>	'Mostrar la versión de FluxBB en el pie de página.',
'Info in posts label'				=>	'Información del usuario en los mensajes',
'Info in posts help'				=>	'Muestra información del usuario que puso el mensaje en la vista de mensajes. La información que se mostrara es localización, fecha de registro, numero de mensajes y formas de contacto (correo electrónico y URL).',
'Post count label'					=>	'Contador de mensajes del usuario',
'Post count help'					=>	'Muestra el número total de mensajes del usuario (afecta a la vista de temas, perfil y lista de usuarios).',
'Smilies label'						=>	'Emoticonos en mensajes',
'Smilies help'						=>	'Convierte los emoticonos en imágenes pequeñas.',
'Smilies sigs label'				=>	'Emoticonos en firmas',
'Smilies sigs help'					=>	'Convierte los emoticonos en imágenes pequeñas en las firmas de los usuarios.',
'Clickable links label'				=>	'Convertir enlaces',
'Clickable links help'				=>	'Si esta habilitado, FluxBB detecta automáticamente las URLs en los mensajes y los convierte en enlaces visitables.',
'Topic review label'				=>	'Revisión de los temas',
'Topic review help'					=>	'Numero máximo de mensajes que se mostrarán mientras se escribe (el más reciente será el primero). Poner a 0 para desactivarlo.',
'Topics per page label'				=>	'Temas por página',
'Topics per page help'				=>	'El número de temas que se mostrarán por página por defecto. Los usuarios pueden personalizar esta opción.',
'Posts per page label'				=>	'Mensajes por página',
'Posts per page help'				=>	'El número de mensajes que se mostrarán por página por defecto. Los usuarios pueden personalizar esta opción.',
'Indent label'						=>	'Tamaño de la sangría',
'Indent help'						=>	'Si el valor es 8, se usara una tabulación normal para mostrar el texto entre las etiquetas [code][/code]. Para otros valores se usarán espacios.',
'Quote depth label'					=>	'Máximos [quote] anidados',
'Quote depth help'					=>	'El máximo de etiquetas [quote] que puede haber dentro de otras etiquetas [quote], el resto se ignorarán.',

// Features section
'Features subhead'					=>	'Funcionalidades',
'Quick post label'					=>	'Respuesta rápida',
'Quick post help'					=>	'Si está habilitado, FluxBB añadirá automáticamente un formulario de respuesta rápida. Los usuarios podrán responder directamente desde la vista del tema.',
'Users online label'				=>	'Usuarios en línea',
'Users online help'					=>	'Muestra en la página principal una lista con el total de visitantes y usuarios registrados en línea.',
'Censor words label'				=>	'Censurar palabras',
'Censor words help'					=>	'Habilita esta opción para censurar palabras en el foro. Ve %s para más información.',
'Signatures label'					=>	'Firmas',
'Signatures help'					=>	'Los usuarios pueden añadir una firma en sus mensajes.',
'User ranks label'					=>	'Rangos de usuario',
'User ranks help'					=>	'Activa esto para usar rangos de usuario. Ve %s para mas información.',
'User has posted label'				=>	'El usuario ha escrito un mensaje anteriormente',
'User has posted help'				=>	'Esta función muestra un punto delante de los temas en viewforum.php en caso de que el usuario que ha iniciado sesión haya publicado en ese tema antes. Desactívalo si estás experimentando una carga alta en el servidor.',
'Topic views label'					=>	'Número de vistas de tema',
'Topic views help'					=>	'Mantener un registro del número de visitas de cada tema. Desactívalo si estás experimentando una carga alta en el servidor.',
'Quick jump label'					=>	'Salto rápido',
'Quick jump help'					=>	'Habilita la lista de salto rápido (saltar a foro).',
'GZip label'						=>	'Salida GZip',
'GZip help'							=>	'Si se activa, FluxBB enviará la página comprimida en gzip al navegador. Esto reduce el ancho de banda, pero consume un poco más de CPU. Esta función sólo funciona si PHP esta configurado para usar zlib (--with-zlib). Nota: si tienes activados los módulos para Apache mod_gzip o mod_deflate para comprimir scripts PHP, deberías desactivar esta función.',
'Search all label'					=>	'Buscar en todos los foros',
'Search all help'					=>	'Si está deshabilitado, sólo se podrá buscar en un foro. Desactívalo si ves que el servidor está sobrecargado debido a muchas peticiones de búsqueda.',
'Menu items label'					=>	'Elementos adicionales en el menú',
'Menu items help'					=>	'En este campo puedes añadir enlaces HTML que se mostrarán en el menú superior. El formato para añadir enlaces es X = &lt;a href="URL"&gt;LINK&lt;/a&gt; Donde X es la posición en la cual se insertará (por ejemplo, 0 lo inserta antes y 2 después de "Lista de usuarios"). Separa las entradas con saltos de línea.',
'Default feed label'				=>	'Tipo de feed por defecto',
'Default feed help'					=>	'Selecciona el sistema de feed por defecto. Nota: si seleccionas ninguno, no los desactivas, sólo los ocultas.',
'None'								=>	'Ninguno',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',

// Reports section
'Reports subhead'					=>	'Reportes',
'Reporting method label'			=>	'Modo de reporte',
'Internal'							=>	'Internos',
'By e-mail'							=>	'Correo electrónico',
'Both'								=>	'Ambos',
'Reporting method help'				=>	'Selecciona el sistema que se usará para manejar reportes de temas/mensajes. Puedes elegir entre el sistema interno de reportes, mediante la lista de correo (ver abajo) o ambos.',
'Mailing list label'				=>	'Lista de correo',
'Mailing list help'					=>	'Lista de usuarios separados por comas. A la gente de esta lista se les enviarán los reportes.',

// Avatars section
'Avatars subhead'					=>	'Avatares',
'Use avatars label'					=>	'Usar avatares',
'Use avatars help'					=>	'Si está activado, los usuarios podrán subir avatares, que serán mostrados encima de su rango/título.',
'Upload directory label'			=>	'Directorio de subida',
'Upload directory help'				=>	'Directorio donde se subirán los avatares (relativo al directorio root de FluxBB ). PHP debe de tener permisos de escritura en el.',
'Max width label'					=>	'Ancho máximo',
'Max width help'					=>	'El ancho máximo de los avatares en píxeles (se recomienda 60).',
'Max height label'					=>	'Alto máximo',
'Max height help'					=>	'El alto máximo de los avatares en píxeles (se recomienda 60).',
'Max size label'					=>	'Tamaño',
'Max size help'						=>	'El tamaño máximo de los avatares en bytes (se recomienda 10240 (10KB)).',

// E-mail section
'E-mail subhead'					=>	'Correo electrónico',
'Admin e-mail label'				=>	'Correo del administrador',
'Admin e-mail help'					=>	'La dirección de correo del administrador del foro.',
'Webmaster e-mail label'			=>	'Correo del webmaster',
'Webmaster e-mail help'				=>	'Esta es la dirección de la que vendrán todos los mensajes enviados por el foro.',
'Subscriptions label'				=>	'Suscripciones',
'Subscriptions help'				=>	'Los usuarios pueden suscribirse a los temas (se les mandará un correo si hubo respuestas nuevas).',
'SMTP address label'				=>	'Dirección del servidor SMTP',
'SMTP address help'					=>	'La dirección de un servidor SMTP externo para usarlo a la hora de enviar correos. Puedes especificar un puerto si el servidor no usa por defecto el puerto 25 (p.e: correo.miservidor.com:3580). Déjalo en blanco para usar el servidor interno.',
'SMTP username label'				=>	'Nombre de usuario SMTP',
'SMTP username help'				=>	'Nombre del usuario del servidor SMTP. Introdúcelo sólo si el servidor lo requiere (muchos servidores <strong>no</strong> requieren autenticación).',
'SMTP password label'				=>	'Contraseña SMTP',
'SMTP password help'				=>	'Contraseña del usuario del servidor SMTP. Introdúcelo sólo si el servidor lo requiere (muchos servidores <strong>no</strong> requieren autenticación.',
'SMTP SSL label'					=>	'Cifrar SMTP con SSL',
'SMTP SSL help'						=>	'Cifra la conexión la conexión al servidor SMTP mediante SSL. Actívalo sólo si es requerido por el servidor SMTP y PHP soporta SSL.',

// Registration Section
'Registration subhead'				=>	'Registro',
'Allow new label'					=>	'Permite nuevos registros',
'Allow new help'					=>	'Controla los nuevos registros en el foro. Desactívalo sólo	 en condiciones especiales.',
'Verify label'						=>	'Verificar registros',
'Verify help'						=>	'Si está activado, se les enviará por correo a los nuevos usuarios una contraseña aleatoria. Esta contraseña puede ser cambiada una vez finalizado el proceso. Esta función también requiere que se verifique la nueva dirección de correo si el usuario la cambió. Este método es efectivo para evitar el registro masivo, además de verificar que la dirección de correo es correcta.',
'Report new label'					=>	'Informar de nuevos registros',
'Report new help'					=>	'Si está activado, FluxBB notificará a los usuarios de la lista de correo (ver arriba) cuando se registre un nuevo usuario.',
'Use rules label'					=>	'Normas del foro',
'Use rules help'					=>	'Si está activado, los usuarios nuevos deben estar de acuerdo con un conjunto de normas para poder registrarse (introduzca el texto abajo). Las normas estarán siempre visibles en el enlace del menú superior en todas las páginas.',
'Rules label'						=>	'Introduce las normas aquí',
'Rules help'						=>	'Aquí puedes introducir cualquier norma u otra información que el usuario debe revisar y aceptar al registrarse. Si activaste las normas antes, tendrás que introducir algo aquí, de lo contrario, se desactivará. Este texto puede contener código HTML.',
'E-mail default label'				=>	'Configuración por defecto del correo',
'E-mail default help'				=>	'Escoja la opción de privacidad del correo de los nuevos usuarios.',
'Display e-mail label'				=>	'Mostrar dirección de correo.',
'Hide allow form label'				=>	'Ocultar dirección de correo y habilitar formulario de contacto.',
'Hide both label'					=>	'Ocultar dirección de correo y deshabilitar formulario de contacto.',

// Announcement Section
'Announcement subhead'				=>	'Anuncios',
'Display announcement label'		=>	'Mostrar anuncio',
'Display announcement help'			=>	'Activar para mostrar el texto de abajo en el foro.',
'Announcement message label'		=>	'Texto del anuncio',
'Announcement message help'			=>	'Este texto puede contener etiquetas HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'Mantenimiento',
'Maintenance mode label'			=>	'Modo de mantenimiento',
'Maintenance mode help'				=>	'Si esta activado, al foro sólo podrán acceder los administradores. Esto debería ser usado si el foro tiene que ser detenido temporalmente por mantenimiento. <strong>¡ATENCIÓN! No cierres sesión mientras está activado.</strong> De lo contrario no podrás acceder de nuevo.',
'Maintenance message label'			=>	'Mensaje de mantenimiento',
'Maintenance message help'			=>	'El mensaje que se mostrará en modo de mantenimiento. Puede contener etiquetas HTML.',

);
