<?php

// Language definitions used in admin_bans.php
$lang_admin_bans = array(

'No user message'			=>	'No hay ningún usuario registrado con ese nombre. Si no quieres banear a un usuario por su nombre, déjalo en blanco.',
'No user ID message'		=>	'No hay ningún usuario registrado con este ID.',
'User is admin message'		=>	'El usuario %s es un administrador y no puede ser baneado. Si quieres banear a un administrador, antes tendrás que relegarlo a moderador o usuario normal.',
'Must enter message'		=>	'Puedes introducir un nombre de usuario, dirección IP o correo.',
'Cannot ban guest message'	=>	'El usuario invitado no puede ser baneado.',
'Invalid IP message'		=>	'Has introducido una dirección IP no válida.',
'Invalid e-mail message'	=>	'La dirección de correo introducida no es válida.',
'Invalid date message'		=>	'La fecha de caducidad no es válida.',
'Invalid date reasons'		=>	'El formato de la fecha debe ser YYYY-MM-DD y al menos un día después de la fecha actual.',
'Ban added redirect'		=>	'Ban añadido. Redirigiendo...' ,
'Ban edited redirect'		=>	'Ban actualizado. Redirigiendo...',
'Ban removed redirect'		=>	'Ban borrado. Redirigiendo...',

'New ban head'				=>	'Nuevo ban',
'Add ban subhead'			=>	'Añadir ban',
'Username label'			=>	'Nombre de usuario',
'Username help'				=>	'El nombre de usuario a banear.',
'Username advanced help'	=>	'El nombre de usuario a banear. En la próxima página podrás introducir una dirección de correo o una dirección/rango de IPs. Si sólo quieres una dirección o rango de IP específico, déjalo en blanco.',

'Ban search head'			=>	'Buscar usuarios baneados',
'Ban search subhead'		=>	'Introduce palabras a buscar',
'Ban search info'			=>	'Buscar baneados en la BD. Puedes introducir una o más palabras a buscar. Puedes usar el carácter especial *.',
'Date help'					=>	'(yyyy-mm-dd)',
'Message label'				=>	'Mensaje',
'Expire after label'		=>	'Expira después de',
'Expire before label'		=>	'Expira antes de',
'Order by label'			=>	'Ordenar por',
'Order by username'			=>	'Nombre del usuario',
'Order by ip'				=>	'IP',
'Order by e-mail'			=>	'Correo',
'Order by expire'			=>	'Fecha de expiración',
'Ascending'					=>	'Ascendente',
'Descending'				=>	'Descendente',
'Submit search'				=>	'Buscar',

'E-mail label'				=>	'Correo',
'E-mail help'				=>	'El correo o dominio del correo a banear (P.E. algo@algo.com o algo.com). Consulta la sección "Permitir baneos de correo" en Permisos para más información.',
'IP label'					=>	'Dirección/Rangos IP',
'IP help'					=>	'La dirección o rango de IP a banear (P.E. 150.11.110.1 o 150.11.110). Separa las IP por espacios. Comprueba que la dirección dada es la que esta registrada en la BD del usuario a banear.',
'IP help link'				=>	'Pulsa %s para ver las estadísticas IP del usuario.',
'Ban advanced head'			=>	'Configuración avanzada del baneo',
'Ban advanced subhead'		=>	'Banear por IP y dirección de correo',
'Ban message label'			=>	'Mensaje de baneo',
'Ban message help'			=>	'Es el mensaje que se mostrará al usuario baneado cuando entre.',
'Message expiry subhead'	=>	'Mensaje de baneo y expiración',
'Ban IP range info'			=>	'Debes de ser muy cuidadoso con los rangos de direcciones IP, ya que podrías banear a otros usuarios que estén en el mismo rango.',
'Expire date label'			=>	'Fecha de expiración',
'Expire date help'			=>	'La fecha en la que el baneo expirará automáticamente (formato: yyyy-mm-dd). Déjalo en blanco para borrar el ban a mano.',

'Results head'				=>	'Resultados de la búsqueda',
'Results username head'		=>	'Nombre del usuario',
'Results e-mail head'		=>	'Correo',
'Results IP address head'	=>	'Dirección/Rangos IP',
'Results expire head'		=>	'Expira',
'Results message head'		=>	'Mensaje',
'Results banned by head'	=>	'Baneado por',
'Results actions head'		=>	'Acciones',
'No match'					=>	'No hay resultados',
'Unknown'					=>	'Desconocido',

);
