<?php

// Language definitions used in admin_index.php
$lang_admin_index = array(

'fopen disabled message'			=>	'No se pueden comprobar las actualizaciones ya que \'allow_url_fopen\' está desactivado en este sistema.',
'Upgrade check failed message'		=>	'Ocurrió un error desconocido al comprobar las actualizaciones.',
'Running latest version message'	=>	'Tienes la ultima versión de FluxBB.',
'New version available message'		=>	'Hay una nueva versión de FluxBB. Puedes descargarla desde %s.',
'PHPinfo disabled message'			=>	'La función de PHP phpinfo() está desactivada.',
'Not available'						=>	'No disponible',
'Forum admin head'					=>	'Administración del foro',
'NA'								=>	'N/D',
'Welcome to admin'					=>	'Bienvenido al panel de administración de FluxBB. Desde aquí puedes controlar las opciones principales del foro. Dependiendo de tu rango puedes:',
'Welcome 1'							=>	'Organizar categorías y foros.',
'Welcome 2'							=>	'Cambiar preferencias y opciones de todo el foro.',
'Welcome 3'							=>	'Controlar los permisos de los usuarios y visitantes.',
'Welcome 4'							=>	'Ver las estadísticas IP de los usuarios.',
'Welcome 5'							=>	'Banear usuarios.',
'Welcome 6'							=>	'Censurar palabras.',
'Welcome 7'							=>	'Cambiar rangos de los usuarios.',
'Welcome 8'							=>	'Borrar temas antiguos.',
'Welcome 9'							=>	'Ver los reportes de mensajes.',
'Statistics head'					=>	'Estadísticas',
'FluxBB version label'				=>	'Versión de FluxBB',
'Check for upgrade'					=>	'Comprobar actualizaciones',
'FluxBB version data'				=>	'v%s - %s',
'Server load label'					=>	'Carga del servidor',
'Server load data'					=>	'%s - %s usuario(s) en linea',
'Environment label'					=>	'Entorno',
'Environment data OS'				=>	'Sistema operativo: %s',
'Show info'							=>	'Ver información',
'Environment data version'			=>	'PHP: %s - %s',
'Environment data acc'				=>	'Acelerador: %s',
'Turck MMCache'						=>	'Turk MMCache',
'Turck MMCache link'				=>	'turck-mmcache.sourceforge.net',
'ionCube PHP Accelerator'			=>	'ionCube PHP Accelerator',
'ionCube PHP Accelerator link'		=>	'www.php-accelerator.co.uk/',
'Alternative PHP Cache (APC)'		=>	'Alternative PHP Cache (APC)',
'Alternative PHP Cache (APC) link'	=>	'www.php.net/apc/',
'Zend Optimizer'					=>	'Zend Optimizer',
'Zend Optimizer link'				=>	'www.zend.com/products/guard/zend-optimizer',
'eAccelerator'						=>	'eAccelerator',
'eAccelerator link'					=>	'www.eaccelerator.net/',
'XCache'							=>	'XCache',
'XCache link'						=>	'xcache.lighttpd.net/',
'Database label'					=>	'Base de datos',
'Database data rows'				=>	'Filas: %s',
'Database data size'				=>	'Tamaño: %s',

);
