<?php

// Language definitions used in admin-options.php
$lang_admin_options = array(

'Bad HTTP Referer message'			=>	'HTTP_REFERER invalido. Si movió el foro o cambio el dominio, debes de editar la nueva url manualmente (mira el valor de o_base_url en la tabla de configuración) y borre todos los archivos *.php del directorio /cache.',
'Must enter title message'			=>	'Introduzca aquí el titulo de su foro.',
'Invalid e-mail message'			=>	'La dirección de correo del administrador es invalida.',
'Invalid webmaster e-mail message'	=>	'La dirección de correo del webmaster es invalida.',
'Enter announcement here'			=>	'Introduce el anuncio aquí.',
'Enter rules here'					=>	'Introduce las normas aquí.',
'Default maintenance message'		=>	'Los foros están en mantenimiento. Vuelva pasado unos minutos.',
'Timeout error message'				=>	'El valor de "Tiempo de espera en linea" debe de ser menor que el de "Tiempo de espera entre visitas".',
'Options updated redirect'			=>	'Opciones actualizadas. Redirigiendo …',
'Options head'						=>	'Opciones',

// Essentials section
'Essentials subhead'				=>	'Esenciales',
'Board title label'					=>	'Titulo del foro',
'Board title help'					=>	'El titulo del foro (se mostrara arriba en todas las paginas). Este campo <strong>no</strong> puede contener código HTML.',
'Board desc label'					=>	'Descripción del foro',
'Board desc help'					=>	'Una descripción corta del foro (se mostrara arriba en todas las paginas). Este campo puede contener código HTML.',
'Base URL label'					=>	'URL Base',
'Base URL help'						=>	'La dirección completa del foro, sin barra al final (p.e. http://www.mipagina.com/foros). Esta <strong>debe</strong> de estar correctamente escrita para que las acciones de los moderadores y administradores funcionen. Si recibe un error de HTTP_REFERER invalido, deberá de cambiarlo.',
'Timezone label'					=>	'Zona horaria por defecto',
'Timezone help'						=>	'La zona horario por defecto para los visitantes y los usuarios que no cambien este valor.',
'DST label'							=>	'Horario de verano',
'DST help'							=>	'Comprueba si se esta en horario de verano (1 hora mas).',
'Language label'					=>	'Idioma por defecto',
'Language help'						=>	'El idioma por defecto para los visitantes y los usuarios que no cambien este valor. Si borras un idioma, este se borrara automáticamente de la lista.',
'Default style label'				=>	'Estilo por defecto',
'Default style help'				=>	'El estilo por defecto para los visitantes y los usuarios que no cambien este valor.',

// Essentials section timezone options
'UTC-12:00'							=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'							=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'							=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'							=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'							=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'							=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'							=>	'(UTC-08:00) Pacific',
'UTC-07:00'							=>	'(UTC-07:00) Mountain',
'UTC-06:00'							=>	'(UTC-06:00) Central',
'UTC-05:00'							=>	'(UTC-05:00) Eastern',
'UTC-04:00'							=>	'(UTC-04:00) Atlantic',
'UTC-03:30'							=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'							=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'							=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'							=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'								=>	'(UTC) Western European, Greenwich',
'UTC+01:00'							=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'							=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'							=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'							=>	'(UTC+03:30) Iran',
'UTC+04:00'							=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'							=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'							=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'							=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'							=>	'(UTC+05:45) Nepal',
'UTC+06:00'							=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'							=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'							=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'							=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'							=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'							=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'							=>	'(UTC+09:30) Australian Central',
'UTC+10:00'							=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'							=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'							=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'							=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'							=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'							=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'							=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'							=>	'(UTC+14:00) Line Islands',

// Timeout Section
'Timeouts subhead'					=>	'Tiempo y tiempos de espera',
'Time format label'					=>	'Formato horario',
'PHP manual'						=>	' manual PHP',
'Time format help'					=>	'[Formato actual: %s]. consulta el %s para mas información.',
'Date format label'					=>	'Formato de la fecha',
'Date format help'					=>	'[Formato actual: %s]. consulta el %s para mas información.',
'Visit timeout label'				=>	'Tiempo de espera entre visitas',
'Visit timeout help'				=>	'Numero de segundos que pasaran para actualizar cuando fue la ultima visita del usuario (afecta principalmente al aviso de nuevos mensajes).',
'Online timeout label'				=>	'Tiempo de espera en linea',
'Online timeout help'				=>	'Numero en segundos que pasaran para comprobar si el usuario no esta en linea y borrarlo de la lista de usuarios en linea.',
'Redirect time label'				=>	'Tiempo de redirección',
'Redirect time help'				=>	'Numero en segundos que durara los mensajes de aviso. Si el valor es 0, estos no se mostraran (No recomendado).',

// Display Section
'Display subhead'					=>	'Vista',
'Version number label'				=>	'Mostrar versión',
'Version number help'				=>	'Mostrar la versión de FluxBB en el pie.',
'Info in posts label'				=>	'Información del usuario en los mensjes',
'Info in posts help'				=>	'Muestra información del posteador en la vista de mensajes. La información que se mostrara es Localización, fecha de registro, numero de mensajes y formas de contacto (Correo electrónico, URL y Mensaje privado).',
'Post count label'					=>	'Contador mensajes del usuario',
'Post count help'					=>	'Muestra el numero total de mensajes del usuario  (afecta a la vista de temas, perfil y lista de usuarios).',
'Smilies label'						=>	'Emoticonos en mensajes',
'Smilies help'						=>	'Convierte los emoticonos en imágenes pequeñas.',
'Smilies sigs label'				=>	'Emoticonos en firmas',
'Smilies sigs help'					=>	'Convierte los emoticonos en imágenes pequeñas en las firmas de los usuarios.',
'Clickable links label'				=>	'Convertir enlaces',
'Clickable links help'				=>	'Si esta habilitado, FluxBB detecta automaticamte URLs en los mensajes y los convierte en enlaces visitables.',
'Topic review label'				=>	'Topic review',
'Topic review help'					=>	'Numero maximo de mensajes que se mostraran mientras se escribe (salvo el primero). Poner a 0 para desactivarlo.',
'Topics per page label'				=>	'Temas por pagina',
'Topics per page help'				=>	'El total de temas que mostraran por pagina por defecto. Los usuarios pueden personalizar esta opción.',
'Posts per page label'				=>	'Mensajes por linea',
'Posts per page help'				=>	'El total de mensajes que mostraran por pagina por defecto. Los usuarios pueden personalizar esta opción.',
'Indent label'						=>	'Tamaño de la sangria',
'Indent help'						=>	'Si el valor es 8, se usara una tabulación normal para mostrar el texto entre las etiquetas [code][/code]. Para otros valores se usaran espacios.',
'Quote depth label'					=>	'Máximos [quote] anidados',
'Quote depth help'					=>	'El máximo de etiquetas [quote] que puede haber dentro de otras etiquetas [quote], el resto se ignoraran.',

// Features section
'Features subhead'					=>	'Features',
'Quick post label'					=>	'Respuesta rapida',
'Quick post help'					=>	'Si esta habilitado, FluxBB añadirá automáticamente un formulario de respuesta rápida. Los usuarios podrán responder directamente desde la vista del tema.',
'Users online label'				=>	'Usuarios en linea',
'Users online help'					=>	'Muestra en la pagina principal una lista con el total de visitantes y usuarios registrados en linea.',
'Censor words label'				=>	'Censurar palabras',
'Censor words help'					=>	'Habilita esta opción para censurar palabras en el foro. Ver %s para mas información.',
'Signatures label'					=>	'Firmas',
'Signatures help'					=>	'Los usuarios pueden añadir una firma en sus mensajes.',
'User ranks label'					=>	'Usar rangos',
'User ranks help'					=>	'Habilita los rangos de usuario. Ver %s para mas información.',
'User has posted label'				=>	'El usuario publico anteriormente',
'User has posted help'				=>	'Esta función muestra un punto delante de los temas en viewforum.php en caso de que el usuario conectado haya publicado en ese tema antes. Desactivar si está experimentando una carga alta del servidor.',
'Topic views label'					=>	'Vista de temas',
'Topic views help'					=>	'Mostrar el numero de visitas del tema. Deshabilitelo si nota una carga alta del servidor.',
'Quick jump label'					=>	'Salto rápido',
'Quick jump help'					=>	'Habilita la lista de salto rápido (Salta a foro).',
'GZip label'						=>	'Salida GZip',
'GZip help'							=>	'Si esta habilitado, FluxBB envia la pagina comprimida en GZIP al navegador. Esto reduce el ancho de banda, pero consume un poco mas de CPU. Esta función solo funciona si PHP esta configurado para usar zlib (--with-zlib). Nota: Si tiene habilitados los modulos para  Apache mod_gzip o mod_deflate para comprimir scripts PHP , deshabilite esta función.',
'Search all label'					=>	'Buscar en todos los foros',
'Search all help'					=>	'Si esta deshabilitado, solo se podra buscar en un foro. Deshabilite si ve que el servidor recibe muchas peticiones de búsqueda.',
'Menu items label'					=>	'Elementos adicionales en el menú',
'Menu items help'					=>	'En este campo puede añadir la cantidad de enlaces HTML para mostrarse en el menú superior que desee. El formato para añadir enlaces es X = &lt;a href="URL"&gt;LINK&lt;/a&gt; Donde X es la posición donde se insertara (p.e. 0 lo inserta antes y 2 después de "Lista de usuarios"). Separe las entradas con saltos de linea.',
'Default feed label'				=>	'Tipo de feed por defecto',
'Default feed help'					=>	'Seleccione el sistema de feed por defecto. Nota: Si selecciona ninguno, no lo deshabilita, solo lo oculta.',
'None'								=>	'Ninguno',
'RSS'								=>	'RSS',
'Atom'								=>	'Atom',

// Reports section
'Reports subhead'					=>	'Reportes',
'Reporting method label'			=>	'Modo de reporte',
'Internal'							=>	'Interno',
'By e-mail'							=>	'Correo electrónico',
'Both'								=>	'Ambos',
'Reporting method help'				=>	'Seleccione el sistema que se usara para reportar nuevos mensajes o temas. Puede elegir entre el sistema interno de reportes, mediante la lista de correo (ver abajo) o ambos.',
'Mailing list label'				=>	'Lista de correo',
'Mailing list help'					=>	'Lista de usuarios separados por comas. A la gente de esta lista se le enviaran los reportes.',

// Avatars section
'Avatars subhead'					=>	'Avatares',
'Use avatars label'					=>	'Usar avatares',
'Use avatars help'					=>	'Si esta habilitado, los usuarios podran subir avatares, que seran mostrados encima de su rango/titulo.',
'Upload directory label'			=>	'Directorio de subida',
'Upload directory help'				=>	'Directorio donde se subirán los avatares (relativo al directorio root de FluxBB ). PHP debe de tener permisos de escritura en el.',
'Max width label'					=>	'Ancho máximo',
'Max width help'					=>	'El ancho máximo de los avatares en píxeles (se recomienda 60).',
'Max height label'					=>	'Alto máximo',
'Max height help'					=>	'El alto máximo de los avatares en píxeles (se recomienda 60).',
'Max size label'					=>	'Tamaño',
'Max size help'						=>	'El peso maximo de los avatares en bytes (se recomienda 10240 (100kb)).',

// E-mail section
'E-mail subhead'					=>	'Correo electrónico',
'Admin e-mail label'				=>	'Correo del administrador',
'Admin e-mail help'					=>	'La dirección de correo del administrados del foro.',
'Webmaster e-mail label'			=>	'Correo del webmaster',
'Webmaster e-mail help'				=>	'El correo del webmaster. Es el que se usara en el campo From de los correos enviados .',
'Subscriptions label'				=>	'Suscripciones',
'Subscriptions help'				=>	'Los usuarios pueden suscribirse a los temas (se les mandara un correo si hubo respuestas nuevas.',
'SMTP address label'				=>	'Dirección del servidor SMTP',
'SMTP address help'					=>	'La dirrección de un servidor SMTP externo para usarlo a la hora de enviar correos. Puedes especificar un puerto si el servidor no usa por defecto el puerto 25 (p.e: correo.miservidor.com:3580). Dejar en blanco para usar el servidor interno.',
'SMTP username label'				=>	'Nombre del usuario SMTP',
'SMTP username help'				=>	'Nombre del usuario del servidor SMTP. Solo introduzca-lo si el servidor lo requiere (muchos servidores <strong>no</strong> requieren autenticación).',
'SMTP password label'				=>	'Contraseña SMTP',
'SMTP password help'				=>	'Contraseña del usuario del servidor SMTP. Solo introduzca-lo si el servidor lo requiere (muchos servidores <strong>no</strong> requieren autenticación.',
'SMTP SSL label'					=>	'Encriptar SMTP con SSL',
'SMTP SSL help'						=>	'Encripta la conexión la conexión al servidor SMTP mediante SSL. Activelo solo si es requerido por el servidor SMTP y PHP soporta SSL.',

// Registration Section
'Registration subhead'				=>	'Registro',
'Allow new label'					=>	'Habilitar nuevos registros',
'Allow new help'					=>	'Controla los nuevos registros en el foro. Desabilitalo solo en condiciones especiales.',
'Verify label'						=>	'Verificar registros',
'Verify help'						=>	'Si esta habilitado, se les mandara a los nuevos usuarios una contraseña aleatoria. Esta contraseña puede ser cambiada una vez finalizado el proceso. Esta función también requiere que se verifique la nueva dirección de correo si el usuario la cambio. Este método es efectivo para evitar el registro masivo, además de verificar que la dirección de correo es la correcta.',
'Report new label'					=>	'Reportar nuevos registros',
'Report new help'					=>	'Si esta habilitado, FluxBB notificara a los usuarios de la lista de correo (ver arriba) cuando se registro un nuevo usuario.',
'Use rules label'					=>	'Normas del foro',
'Use rules help'					=>	'Si esta habilitado, mostrara las normas del foro que los usuarios nuevos deben de aceptar (introduzca el texto abajo). Las normas estarán siempre visibles en el enlace del menú superior en todas las paginas.',
'Rules label'						=>	'Introduce las normas aqui',
'Rules help'						=>	'Aquí puede introducir cualquier norma u otra información que el usuario debe revisar y aceptar al registrarse. Si habilitó normas antes, tendrá que introducir algo aquí, de lo contrario, se desactivará. Este texto puede contener codigo HTML.',
'E-mail default label'				=>	'Configuración por defecto del correo',
'E-mail default help'				=>	'Escoja la opción de privacidad del correo de los nuevos usuarios.',
'Display e-mail label'				=>	'Mostrar dirección de correo.',
'Hide allow form label'				=>	'Ocultar dirección de correo y habilitar formulario de contacto.',
'Hide both label'					=>	'Ocultar dirección de correo y deshabilitar formulario de contacto.',

// Announcement Section
'Announcement subhead'				=>	'Anuncios',
'Display announcement label'		=>	'Mostrar anuncio',
'Display announcement help'			=>	'Habilitar para mostrar el texto de abajo en el foro.',
'Announcement message label'		=>	'Texto del anuncio',
'Announcement message help'			=>	'Este texto puede contener etiquetas HTML.',

// Maintenance Section
'Maintenance subhead'				=>	'Mantenimiento',
'Maintenance mode label'			=>	'Modo de mantenimiento',
'Maintenance mode help'				=>	'Si esta habilitado, al foro solo podran acceder los administradores. Esto es usado si el foro cerrara temporalmente por temas de mantenimento. <strong>!Atención! No cierre sesión si esta habilitado.</strong> De lo contrario no podrá acceder de nuevo.',
'Maintenance message label'			=>	'Mensaje de mantenimiento',
'Maintenance message help'			=>	'El mensaje que se mostrar en modo de mantenimiento. Puede contener etiquetas HTML.',

);
