<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Introduzca una dirección de correo valida',
'Email legend 2'			=>	'Introduzca y confirme una dirección de correo valida',
'Localisation legend'		=>	'Escoja las opciones de localización',
'Time zone'					=>	'Zona horaria',
'Time zone info'			=>	'Para visualizar correctamente las horas correctamente, escoja su zona horaria.',
'DST'						=>	'Detectar horario de verano.',
'Time format'				=>	'Formato de la hora',
'Date format'				=>	'Formato de la fecha',
'Default'					=>	'Por defecto',
'Language'					=>	'Idioma',
'Email setting info'		=>	'Seleccione si quiere que la gente pueda ver su dirección de correo y/o pueden mandarle uno desde el foro.',
'Email setting 1'			=>	'Ver dirección de correo.',
'Email setting 2'			=>	'Ocultar correo y activar formulario de contacto.',
'Email setting 3'			=>	'Ocultar correo y desactivar formulario de contacto.',
'Privacy options legend'	=>	'Elija las opciones de privacidad',
'Confirm pass'				=>	'Confirmar contraseña',

'Username too short'		=>	'El nombre del usuario debe de tener al menos 2 caracteres.',
'Username too long'			=>	'El nombre del usuario no debe tener mas de 25 caracteres.',
'Username guest'			=>	'Este nombre de usuario esta reservado.',
'Username IP'				=>	'Los nombres de usuario no pueden estar en un formato similar al de una IP.',
'Username reserved chars'	=>	'El nombre del usuario no puede contener \', " y [ o ].',
'Username BBCode'			=>	'El nombre del usuario no pude contener etiquetas BBCode.',
'Banned username'			=>	'Este nombre de usuario esta baneado.',
'Pass too short'			=>	'Las contraseñas deben de tener mas de 4 caracteres.',
'Pass not match'			=>	'Las contraseñas no coinciden.',
'Banned email'				=>	'La dirección de correo esta baneada.',
'Dupe email'				=>	'Ya hay otro usuario registrado con esta dirección de correo.',
'Sig too long'				=>	'Las firmas no pueden tener mas de',
'characters'				=>	'caracteres',
'Sig too many lines'		=>	'Las firmas no pueden tener mas de',
'lines'						=>	'lineas',
'Bad ICQ'					=>	'Has introducido un ICQ UIN erróneo.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
